#!/bin/bash

# Extract executable tasks from plan/{n}/{role}/*.md drafts into tasks.md
# Only entries with `task:` lines become executor tasks.
# Reviewer observations (no task: line) are excluded.
#
# Usage: ./v84-docs/scripts/executor/extract.sh <iteration>
# Output: plan/{n}/tasks.md

set -euo pipefail

ITERATION="${1:?Usage: executor/extract.sh <iteration>}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
PLAN_DIR="${REPO_ROOT}/v84-docs/plan/${ITERATION}"
PLAN_FILE="${PLAN_DIR}.md"
OUTPUT="${PLAN_DIR}/tasks.md"

if [ ! -d "$PLAN_DIR" ]; then
  echo "Error: plan directory ${PLAN_DIR} does not exist" >&2
  exit 1
fi

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

task_count=0

# Walk plan/{n}/{role}/{topic}.md — skip raw/, logs/, lead.md
for role_dir in "${PLAN_DIR}"/*/; do
  [ -d "$role_dir" ] || continue
  role=$(basename "$role_dir")
  case "$role" in
    raw|logs) continue ;;
  esac

  for file in "$role_dir"*.md; do
    [ -f "$file" ] || continue
    topic=$(basename "$file" .md)
    [ "$topic" = "lead" ] && continue

    agent_tag="${role}:${topic}"
    seq=0
    entry_file=""
    has_task=false

    flush_entry() {
      if [ -n "$entry_file" ] && [ -f "$entry_file" ]; then
        if $has_task; then
          task_count=$((task_count + 1))
        else
          rm "$entry_file"
        fi
      fi
    }

    while IFS= read -r line || [ -n "$line" ]; do
      if [[ "$line" =~ ^\[v84-[0-9] ]]; then
        flush_entry
        seq=$((seq + 1))
        has_task=false
        raw_tag=$(echo "$line" | grep -oP '\[v84-[0-9][^\]]*\]' | tr -d '[]' | sed 's/#.*//')
        sort_key=$(echo "$raw_tag" | sed 's/v84-//' | awk -F'-' '{
          for(i=1;i<=NF;i++) printf "%03d-", $i
        }' | sed 's/-$//')
        entry_file="${TMPDIR}/${sort_key}_${role}_${topic}_$(printf '%04d' $seq).entry"
        echo "[${agent_tag}] ${line}" > "$entry_file"
      elif [ -n "$entry_file" ]; then
        echo "$line" >> "$entry_file"
        if [[ "$line" =~ ^[[:space:]]+task: ]]; then
          has_task=true
        fi
      fi
    done < "$file"

    flush_entry
  done
done

if [ "$task_count" -eq 0 ]; then
  echo "No tasks found in plan/${ITERATION}/ drafts" >&2
  {
    echo "# Tasks — Iteration ${ITERATION}"
    echo ""
    echo "No executable tasks found."
  } > "$OUTPUT"
  exit 0
fi

# Parse plan file for tag descriptions
declare -A plan_text
current_plan_tag=""
current_plan_desc=""

flush_plan() {
  if [ -n "$current_plan_tag" ]; then
    plan_text["$current_plan_tag"]="$current_plan_desc"
  fi
}

if [ -f "$PLAN_FILE" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    if [[ "$line" =~ ^##[#]?[[:space:]]+\[v84- ]]; then
      flush_plan
      current_plan_tag=$(echo "$line" | grep -oP '\[v84-[0-9][^\]]*\]')
      current_plan_desc=""
    elif [ -n "$current_plan_tag" ] && [ -n "$line" ]; then
      if [ -n "$current_plan_desc" ]; then
        current_plan_desc="${current_plan_desc}
${line}"
      else
        current_plan_desc="$line"
      fi
    fi
  done < "$PLAN_FILE"
  flush_plan
fi

# Output sorted tasks grouped by plan tag
{
  echo "# Tasks — Iteration ${ITERATION}"
  echo "# Auto-generated by executor/extract.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "#"
  echo "# Only entries with task: lines. Executor reads top-to-bottom."
  echo "# Check depends: before starting each task."
  echo ""

  current_group=""
  for entry_file in $(ls "${TMPDIR}"/*.entry 2>/dev/null | sort); do
    tag=$(head -1 "$entry_file" | grep -oP '\[v84-[0-9][^\]]*\]' | head -1 | sed 's/#.*//')

    if [ "$tag" != "$current_group" ]; then
      if [ -n "$current_group" ]; then
        echo ""
      fi
      echo "## ${tag}"
      desc="${plan_text[$tag]:-}"
      if [ -n "$desc" ]; then
        echo "$desc"
      fi
      echo ""
      current_group="$tag"
    fi

    cat "$entry_file"
    echo ""
  done
} > "$OUTPUT"

# Append needs: summary
needs_lines=$(grep -rh "^  needs:" "${PLAN_DIR}"/*/*.md 2>/dev/null | sort -u || true)
if [ -n "$needs_lines" ]; then
  {
    echo ""
    echo "---"
    echo "## Dependencies to install first"
    echo ""
    echo "$needs_lines" | while read -r line; do
      echo "- ${line#  needs: }"
    done
  } >> "$OUTPUT"
fi

echo "Extracted: ${OUTPUT}"
echo "Tasks: ${task_count} (reviewer observations excluded)"
